-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUEccKnyZBg7Q21er
IfiFqtH4FVmz6Lc/7+CeOLVADlSgCgYIKoZIzj0DAQehRANCAARKn3ovMcBl83Qb
wUsKueVAvOjCwQMCmxzYd+kxvfwFhzWQxI6XRlghlQk5pcKTDEcaG66FovI2oLw1
y7PnVy7I
-----END PRIVATE KEY-----